# Generated by Django 5.2.1 on 2025-06-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назва послуги', max_length=100)),
                ('description', models.TextField(help_text='Опис послуги')),
            ],
        ),
    ]
